### ISSUE TITLE
Hi, 请问原始数据集可以发我一份吗？

### ISSUE THREAD

**Issue by mJackie** [zhangyingkai/Data-Mining-Case#1]
最近在做相关工作，想用DC竞赛上的微博热度预测这个数据集，可以发我一份吗？谢谢

**Comment by zhangyingkai** [comment]
加油


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jackie.Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午5:37
收件人:&nbsp;"zhangyingkai/Data-Mining-Case"<Data-Mining-Case@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[zhangyingkai/Data-Mining-Case] Hi, 请问原始数据集可以发我一份吗？ (#1)




最近在做相关工作，想用DC竞赛上的微博热度预测这个数据集，可以发我一份吗？谢谢
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

userRelations.zip (2.05G, 2020年01月18日 20:08 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=22323137672e7a442568c576133154165d00020f5303510c49000855511c525f01571c0f57500014500550045000020a010b04073520664c17574365505d074d0d5d5f441b4b0f49640f&t=exs_ftn_download&code=d21751f9




WeiboProfile.test (1.05M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=243330652e7ddfcc2369c4241262021c06010550520104564f060803054f040b52061d5c035b531e54055601550602060600035d34733064075a520a64105f550b5f554b40074347620e&t=exs_ftn_download&code=b30e4b03




WeiboProfile.train (9.01M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2230383244dc0cca246acc734535511a01550a5306535a5148565b04051857515704150a5451001851090a055256025754055d546327636200595a5d33470c530c5c5d1c1747025c0b3005&t=exs_ftn_download&code=e082c5c5




微博热度预测.docx (1.09M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7e65353756a8df9e793fc1761434034e0e5654065606525315570d51021905585950180f5052504c09070501060757535c525300322531af9ad79cfffa82f9b59cd7d719565b52193858&t=exs_ftn_download&code=8e57241a




testRepostBeforeFirstHour.txt (28.21M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=30396463a9ae059a2363902212330b4b5b0b060506505b504f5c5550521e0d54540a4901550b0f495b0a5d0200030857515f5456342e3910074a103151435617167b01055b415c220b4b17177c5c4c164c4d1c17340e&t=exs_ftn_download&code=b9dc439d

**Comment by mJackie** [comment]
非常感谢，thx

**Comment by zhangyingkai** [comment]
这是全部的了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jackie.Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 晚上9:55
收件人:&nbsp;"zhangyingkai/Data-Mining-Case"<Data-Mining-Case@noreply.github.com&gt;;
抄送:&nbsp;"张英凯"<1106532929@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangyingkai/Data-Mining-Case] Hi, 请问原始数据集可以发我一份吗？ (#1)




非常感谢，thx
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

trainRepost.txt (1018.47M, 2020年01月18日 22:05 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=72326236fe026af97768967743650016525451075051570f1b0555545048060005574f0e5c070b1405530457015c570801045553656a324d44530b583700425645464c421d113204&t=exs_ftn_download&code=62b6ee29

**Comment by mJackie** [comment]
谢谢，太感谢了
